### ISSUE TITLE
Lacks Python 3 support

### ISSUE THREAD

**Issue by OOOlledj** [stewartadam/fwbackups#13]
### System Details
- fwbackups version: 1.43.7
- OS name and version: Ubuntu 20.04.2 LTS (xubuntu)

### Issue description
I have many compilation errors while making source code. 
First it was "./configure" - intltool version lower than 0.35.0, i upgraded it to 0.51.0, then everything ok.
But while it was making (make install), i observed compilation errors (listed below)

### Bug details
Steps to Reproduce:

1. ./configure (ok)
2. make (ok)
3. sudo make install (error occurs)

Observed results: Errors while makeinstalling

Expected results: Installation

```
Making install in bin
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/bin'
make[2]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/bin'
make[2]: Nothing to be done for 'install-exec-am'.
/bin/bash /home/ooolledj/Downloads/fwbackups-1.43.7/install-sh -d /usr/local/bin
/usr/bin/install -c -m 755 fwbackups /usr/local/bin/fwbackups
/usr/bin/install -c -m 755 fwbackups-run.py /usr/local/bin/fwbackups-run
/usr/bin/install -c -m 755 fwbackups-runonce.py /usr/local/bin/fwbackups-runonce
make[2]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/bin'
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/bin'
Making install in po
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/po'
linguas="de es et fr gl hr id is lt ms nb_NO nl oc pt_BR pt_PT ru sq sv th tr uk "; \
for lang in $linguas; do \
  dir=/usr/local/share/locale/$lang/LC_MESSAGES; \
  /bin/bash /home/ooolledj/Downloads/fwbackups-1.43.7/install-sh -d $dir; \
  if test -r $lang.gmo; then \
    /usr/bin/install -c -m 644 $lang.gmo $dir/fwbackups.mo; \
    echo "installing $lang.gmo as $dir/fwbackups.mo"; \
  else \
    /usr/bin/install -c -m 644 ./$lang.gmo $dir/fwbackups.mo; \
    echo "installing ./$lang.gmo as" \
	 "$dir/fwbackups.mo"; \
  fi; \
  if test -r $lang.gmo.m; then \
    /usr/bin/install -c -m 644 $lang.gmo.m $dir/fwbackups.mo.m; \
    echo "installing $lang.gmo.m as $dir/fwbackups.mo.m"; \
  else \
    if test -r ./$lang.gmo.m ; then \
      /usr/bin/install -c -m 644 ./$lang.gmo.m \
	$dir/fwbackups.mo.m; \
      echo "installing ./$lang.gmo.m as" \
	   "$dir/fwbackups.mo.m"; \
    else \
      true; \
    fi; \
  fi; \
done
installing de.gmo as /usr/local/share/locale/de/LC_MESSAGES/fwbackups.mo
installing es.gmo as /usr/local/share/locale/es/LC_MESSAGES/fwbackups.mo
installing et.gmo as /usr/local/share/locale/et/LC_MESSAGES/fwbackups.mo
installing fr.gmo as /usr/local/share/locale/fr/LC_MESSAGES/fwbackups.mo
installing gl.gmo as /usr/local/share/locale/gl/LC_MESSAGES/fwbackups.mo
installing hr.gmo as /usr/local/share/locale/hr/LC_MESSAGES/fwbackups.mo
installing id.gmo as /usr/local/share/locale/id/LC_MESSAGES/fwbackups.mo
installing is.gmo as /usr/local/share/locale/is/LC_MESSAGES/fwbackups.mo
installing lt.gmo as /usr/local/share/locale/lt/LC_MESSAGES/fwbackups.mo
installing ms.gmo as /usr/local/share/locale/ms/LC_MESSAGES/fwbackups.mo
installing nb_NO.gmo as /usr/local/share/locale/nb_NO/LC_MESSAGES/fwbackups.mo
installing nl.gmo as /usr/local/share/locale/nl/LC_MESSAGES/fwbackups.mo
installing oc.gmo as /usr/local/share/locale/oc/LC_MESSAGES/fwbackups.mo
installing pt_BR.gmo as /usr/local/share/locale/pt_BR/LC_MESSAGES/fwbackups.mo
installing pt_PT.gmo as /usr/local/share/locale/pt_PT/LC_MESSAGES/fwbackups.mo
installing ru.gmo as /usr/local/share/locale/ru/LC_MESSAGES/fwbackups.mo
installing sq.gmo as /usr/local/share/locale/sq/LC_MESSAGES/fwbackups.mo
installing sv.gmo as /usr/local/share/locale/sv/LC_MESSAGES/fwbackups.mo
installing th.gmo as /usr/local/share/locale/th/LC_MESSAGES/fwbackups.mo
installing tr.gmo as /usr/local/share/locale/tr/LC_MESSAGES/fwbackups.mo
installing uk.gmo as /usr/local/share/locale/uk/LC_MESSAGES/fwbackups.mo
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/po'
Making install in pixmaps
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/pixmaps'
make[2]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/pixmaps'
make[2]: Nothing to be done for 'install-exec-am'.
/bin/bash /home/ooolledj/Downloads/fwbackups-1.43.7/install-sh -d /usr/local/share/icons/hicolor/{scalable,128x128,64x64,48x48,32x32,16x16}/apps/
/bin/bash /home/ooolledj/Downloads/fwbackups-1.43.7/install-sh -d /usr/local/share/fwbackups/
/usr/bin/install -c -m 644 fwbackups.svg /usr/local/share/icons/hicolor/scalable/apps/fwbackups.svg
/usr/bin/install -c -m 644 fwbackups-128.png /usr/local/share/icons/hicolor/128x128/apps/fwbackups.png
/usr/bin/install -c -m 644 fwbackups-64.png /usr/local/share/icons/hicolor/64x64/apps/fwbackups.png
/usr/bin/install -c -m 644 fwbackups-48.png /usr/local/share/icons/hicolor/48x48/apps/fwbackups.png
/usr/bin/install -c -m 644 fwbackups-32.png /usr/local/share/icons/hicolor/32x32/apps/fwbackups.png
/usr/bin/install -c -m 644 fwbackups-16.png /usr/local/share/icons/hicolor/16x16/apps/fwbackups.png
/usr/bin/install -c -m 644 fwbackups-32.png /usr/local/share/fwbackups/fwbackups.png
make[2]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/pixmaps'
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/pixmaps'
Making install in src
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src'
make[2]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src'
make[2]: Nothing to be done for 'install-exec-am'.
/bin/bash /home/ooolledj/Downloads/fwbackups-1.43.7/install-sh -d /usr/local/share/applications
/usr/bin/install -c -m 644 fwbackups.desktop /usr/local/share/applications/fwbackups.desktop
 /usr/bin/mkdir -p '/usr/local/share/fwbackups'
 /usr/bin/install -c -m 644 BugReport.glade fwbackups.glade fwbackups-autostart.desktop fwbackups-runapp.pyw '/usr/local/share/fwbackups'
make[2]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src'
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src'
Making install in src/fwbackups/operations
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups/operations'
make[2]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups/operations'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/lib/python3.8/site-packages/fwbackups/operations'
 /usr/bin/install -c -m 644 __init__.py backup.py restore.py '/usr/local/lib/python3.8/site-packages/fwbackups/operations'
<string>:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Byte-compiling python modules...
__init__.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/operations/__init__.py", line 66
    except Exception, error:
                    ^
SyntaxError: invalid syntax

backup.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/operations/backup.py", line 262
    except IOError, description:
                  ^
SyntaxError: invalid syntax

restore.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/operations/restore.py", line 126
    except Exception, error:
                    ^
SyntaxError: invalid syntax


Byte-compiling python modules (optimized versions) ...
__init__.pybackup.pyrestore.py
make[2]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups/operations'
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups/operations'
Making install in src/fwbackups
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups'
make[2]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/lib/python3.8/site-packages/fwbackups'
 /usr/bin/install -c -m 644 config.py const.py cron.py fwlogger.py i18n.py __init__.py interface.py sftp.py shutil_modded.py widgets.py '/usr/local/lib/python3.8/site-packages/fwbackups'
<string>:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Byte-compiling python modules...
config.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/config.py", line 48
    os.mkdir(encode(directory), 0700)
                                   ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

const.pycron.pyfwlogger.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/fwlogger.py", line 68
    except Exception, error:
                    ^
SyntaxError: invalid syntax

i18n.py__init__.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/__init__.py", line 165
    print "You must install PyCron to run this program."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("You must install PyCron to run this program.")?

interface.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/interface.py", line 51
    (`name`, `self.filename`))
     ^
SyntaxError: invalid syntax

sftp.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/sftp.py", line 48
    except IOError, errorDesc:
                  ^
SyntaxError: invalid syntax

shutil_modded.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/shutil_modded.py", line 62
    raise Error, "`%s` and `%s` are the same file" % (src, dst)
               ^
SyntaxError: invalid syntax

widgets.py  File "/usr/local/lib/python3.8/site-packages/fwbackups/widgets.py", line 135
    except UnicodeDecodeError, e:
                             ^
SyntaxError: invalid syntax


Byte-compiling python modules (optimized versions) ...
config.pyconst.pycron.pyfwlogger.pyi18n.py__init__.pyinterface.pysftp.pyshutil_modded.pywidgets.py
make[2]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups'
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7/src/fwbackups'
make[1]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7'
make[2]: Entering directory '/home/ooolledj/Downloads/fwbackups-1.43.7'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7'
make[1]: Leaving directory '/home/ooolledj/Downloads/fwbackups-1.43.7'

```

**Comment by stewartadam** [comment]
fwbackups requires Python 2.x, unfortunately I have not had the time to update it for Python 3 (nor GTK 3). I'm not sure that it is compatible with modern releases like Fedora 33 or Ubuntu 20.x without manually grabbing or compiling compatible packages.

**Comment by OOOlledj** [comment]
Is it possible to force use python2 to make the source?

**Comment by stewartadam** [comment]
Try one of [these](https://stackoverflow.com/questions/46102543/autotools-use-python-2-7-when-python-3-is-available) recommendations to see if you can coax autoconf to use python2 by default. If not, using a python2 container and then copying the files out is probably easiest if you don't want to adjust your system.

**Comment by neilsummers** [comment]
I recently ran into this issue after upgrading to Ubuntu 20.04. With prior Ubuntu releases (18.04) I had been able to maintain Python2 and Python3 simultaneously with all the packages required to run this app, but as of 20.04 I can no longer do this. While I could get fwbackups to work with 20.04 (using `apt install python-is-python2` and then installing all the necessary dependencies through apt as before), I could not without crippling the Python3 environment, which is not acceptable.

I looked into what it would take to do the Python2 -> Python3 migration, and while the Python migration is fairly trivial, the Gtk2 -> 3 is not. This is not something I have time for, so I went with the Docker solution instead. I found a fwbackups-docker solution out there, but it was not very good so I wrote my own.

https://github.com/neilsummers/fwbackups-docker

This provides a wrapper around fwbackups and runs fwbackups in a Docker container containing a Ubuntu 18.04 base image, with scripts installed with the same fwbackups name which encapsulates all the commands needed to run fwbackups in docker, abstracting this away from the user, while maintaining all the start menu and tray icon behaviour as before, and mounting all the files from the localhost needed to run this container therefore keeping all the necessary files on the localhost that need referencing and editing.

This only works for backups to localhost as I have not opened up any ports to do remote backup, but it should be possible if needed. I was only was considering Linux distributions, so no idea what would work on a MS Windows system. Since Python2 is being deprecated, I hope this helps anybody who wants to continue using this very useful backup solution.

**Comment by neilsummers** [comment]
I recently ran into this issue after upgrading to Ubuntu 20.04. With prior Ubuntu releases (18.04) I had been able to maintain Python2 and Python3 simultaneously with all the packages required to run this app, but as of 20.04 I can no longer do this. While I could get fwbackups to work with 20.04 (using apt install python-is-python2 and then installing all the necessary dependencies through apt as before), I could not without crippling the Python3 environment, which is not acceptable.

I looked into what it would take to do the Python2 -> Python3 migration, and while the Python migration is fairly trivial, the Gtk2 -> 3 is not. This is not something I have time for, so I went with the Docker solution instead. I found a fwbackups-docker solution out there, but it was not very good so I wrote my own.
https://github.com/neilsummers/fwbackups-docker

Unfortunately, this is not fully working yet as I've run into some issues with the interaction with cron and read-only volumes in docker, so I tried to install directly in Ubuntu Focal 20.04 instead. The PR #14 shows how I got this working with the latest LTS version of Ubuntu in case anyone else needs helps getting this running again.

**Comment by PunyTRexArms** [comment]
Here is the procedure I used to get fwbackups working two years ago after upgrading to Ubuntu 20.04 LTS:

    sudo apt install gettext autotools-dev intltool python-crypto cron

[How to Install Python Pip on Ubuntu 20.04](https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/#installing-pip-for-python-2)

    pip install paramiko

Add Python 2 repository:

    sudo add-apt-repository ppa:nrbrtx/python2-stuff

Install _python-gtk2_, _python-glade2_, and _python-notify_:

    sudo apt install python-gtk2 python-glade2 python-notify

Now switch to the source directory and configure, make, and install:

    ./configure --prefix=/usr
    make
    sudo make install

Some Ubuntu distributions no longer include the Python `site-packages` directory in their search path, which may prevent **fwbackups** from starting. To remedy this, execute these two lines:

    PYTHONVER=$(python -c 'import sys;print "%s.%s" % (sys.version_info[0], sys.version_info[1])')
    sudo ln -s ../site-packages/fwbackups /usr/lib/python${PYTHONVER}/dist-packages/fwbackups

For other users you will also need to run:

    pip install paramiko

It's worked like a charm since then. However, after recently upgrading to 22.04 LTS I get "/usr/bin/fwbackups: line 30: python: command not found" when attempting to start fwbackups at the command line. Any help would be appreciated.

**Comment by neilsummers** [comment]
@PunyTRexArms While I can't reproduce what is exactly going on without without reproducing your steps (which I'm not prepared to do at this point as I would have to uninstall my working version and follow your steps, then upgrade to 22.04 and try it again, which is too much), I can tell you this from my trials of trying to get this to work, and why I did not use the procedure you outline above (after trying such similar methods, and understanding what it was really doing under the hood).

While you might have got this working before for fwbackups, it wasn't exactly a fully working system, and that is why I posted #14 which is what I think is a more robust way to do it. What I suspect you had, by reading through you steps, is that it installed the python2 packages, which forces the default python in your Ubuntu installation over to python2, and then uses the packages you installed. This breaks the python3 version that Ubuntu now ships with, as it doesn't allow the python2 versions to coexist along with the python3 version by means of the package management system (but since python2 and python3 can be separated this is only by force of the package management system and not a hard depenency, and hence why I wrote #14 which works around this). I need python3, so doing this is not an option for me.
When you run make it just uses the python executable, which after installing your python2 packages is the default, and therefore it runs python2 when running fwbackups.
With the latest Ubuntu verion 22.04, I suspect they have make even more changes deprecating python2 which now breaks this.

I haven't tested my script with 22.04 LTS yet (but I will be doing this soon), but in theory it should still be possible. What my method does is install the python2 packages without changing the default python away from python3. The python2 packages get installed in the python2 directories as usual. I hack the Ubuntu package dependency tree to stop it complaining about installing both python2 and python3 packages, since they can safely coexist on the same system. I then have a fully working python2 and python3 environments which can be called with python2 and python3 repsectively, while python points to python3 as the default.
This is the important part, then when making fwbackups, I specifically point to python2 to be used as the interpreter, even though python3 is the default that python points to. This allows fwbackups to run on python2 while the python3 distribution is not broken.
I suspect that the 22.04 LTS version has even less python2 packages installed (and might even be fully deprecated from that Ubuntu release), so therefore more that what you have specified above will need to be installed to get a fully working python2 version available on your system. You would probably need to actually install the full python2 package as I think it is no longer shipped with that Ubuntu version.

I would suggest using my scripts, but they are not updated to 22.04 yet. I am planning on doing this upgrade soon, in the next few weeks, and will update the scripts when I do this as I figure out what changes need to be made to get it working again. I wanted to get my full dockerized version working so I could fwbackups working in a container that wouldn't need to be continually updated, but alas, I ran into too many docker issues for that to be a reliable method. I hope this makes some sense and helps you understand what is going on. It's a bit long winded and I don't have a quick fix, but it's a difficult problem of keeping old software working on a new system.

**Comment by saiballo** [comment]
> Try one of [these](https://stackoverflow.com/questions/46102543/autotools-use-python-2-7-when-python-3-is-available) recommendations to see if you can coax autoconf to use python2 by default. If not, using a python2 container and then copying the files out is probably easiest if you don't want to adjust your system.

Hi,

fwbackups was (and is) the best backup tool I tried on linux. Today no other software is such complete and flexible as fwbackups.

Any chance to update the software to gtk3? I'm on ubuntu 22.04 and can't install docker. I could donate up to 200 euro for this project.

it's sad let die fwbackups.

**Comment by PunyTRexArms** [comment]
> fwbackups was (and is) the best backup tool I tried on linux. Today no other software is such complete and flexible as fwbackups.

Agreed.

> Any chance to update the software to gtk3? I'm on ubuntu 22.04 and can't install docker. I could donate up to 200 euro for this project.

At this point I would be grateful for an updated version of fwbackups that plays nice with Python 3. I understand that Mr. Adam is reluctant to accept monetary compensation for his work, but nevertheless I would be willing to match your funds if it meant bringing this project back to life.

I compiled my installation of fwbackups before upgrading to 22.04, but now when I run it from the command line I get: `/usr/bin/fwbackups: line 30: python: command not found`. I'm a numerical programmer (Fortran), so I lack the technical knowledge to address this issue.

**Comment by stewartadam** [comment]
Thanks all for the kind words - it's very delightful to hear from passionate users that still find fwbackups useful after all these years! I've found some time to start a porting effort to Python 3 and GTK4, although I'm running into some issues with signals I hope to resolve this weekend.

I appreciate the offers for financial support, but my main bottleneck on this is time - if I can get it working, I would love for you to donate to your favorite charity instead as thanks :)

**Comment by stewartadam** [comment]
I will use this comment as a running list of stuff to resolve before release so the community can keep tabs on my progress. Note this is a non-exhaustive list, as once something gets fixed it opens the door to discover additional things that broke in the GTK2 -> 4 migration.

Functionality:
- [x] Python3 compatibility
- [x] Port GTK2 `.glade` interface descriptor to a GTK4 GtkBuilder `.ui` file
- [x] Application doesn't immediately raise exception on launch
- [ ] Make the main window UI actually show itself post-GTK4 port
- [ ] Fix file selection and status icons in backup path listviews
- [ ] Deprecate automake-based setup in favor of a simple `setup.py`

GTK4 changes:
- [ ] Migrate to use a GtkApplication
- [ ] Refactor notifications to use system notifications via GTK framework
- Revisit use of removed or deprecated features from GTK2
  - [ ] tray icons
  - [ ] tree view
  - [ ] stock icons in dialogs, windows, GtkImage
- [ ] Fix any broken tests
- Refactoring:
   - SSH/SFTP handling:
      - [ ] Revisit use of Paramiko, update to latest APIs
      - [ ] Refactor SFTP backup code to leverage `fabric.transfer`
      - [ ] Support SSH key login?
   - [ ] Redo charset encoding issues now that py3 strings are always unicode strings
   - [ ] Revisit localization/internationalization framework
   - [ ] Update `config.py` to use latest ConfigParser API (py3 implementation is much more sane now)
   - [ ] Fix flake8 lints
- Stretch goals:
   - [ ] Split main application into smaller classes per-window (same for `.ui` descriptors)
   - [ ] Simplify `.ui` file and remove redundant settings
   - [ ] Test on Windows
   - [ ] Test on MacOS
   - [ ] Blog post on migration process (available docs on Python+GTK4 are ***thin***)
   - [ ] Binary app packaging for Linux (flatpak, snap or appimage TBD)
   - [ ] Binary app packaging for Windows and MacOS (possibly pyinstaller?)
   - [ ] Visit possibility of systemd service instead of cron
   - [ ] Revisit the documentation (migrate to something markdown-based)

If folks have thoughts on distribution method (flatpak/snap/appimage), I've been away from the Linux GUI world for a moment so I'd appreciate input.

**Comment by saiballo** [comment]
My two cents:

- If you need I'm available to test development version. I'm on ubuntu 22.04 or 20.04
- my distribution method in preferred order: snap, appimage, flatpak

I agree that snap, appimage etc etc are very convenient in some case. Like this.

**Comment by stewartadam** [comment]
We're getting real close! I'm hoping to have a release candidate out this weekend for folks to start testing.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/77808/210986135-0e405d72-6825-4991-917a-2c42b62c5ef8.png">

**Comment by saiballo** [comment]
wow!! it sounds really cool!!! and you are super fast!!!

Can't wait to try the rc :-)

**Comment by stewartadam** [comment]
Finished the build system, I have to write some docs up and finish app packaging before I can publish the release candidate but the code should be executable right from the repo right now:

```
pip3 install --user poetry
git clone https://github.com/stewartadam/fwbackups.git
cd fwbackups
git checkout feature/gtk4
poetry install
poetry run python3 -m fwbackups
```

**Comment by didier33170** [comment]
Happy New Year everyone !
I started the year by migrating my Mint system to the new Ubuntu-based version 21.1 ("Jammy Jellyfish").
I used fwbackups for years, until it stopped working after a system update. I'm so glad to read that a python 3 compatible version is about to be released. And especially very grateful to Mr. Adams for his work.
I confirm, after a few others on this list, that after trying many other backup apps, fwbackups is definitely my favorite!
Thanks again for your work for the community!

**Comment by didier33170** [comment]
Hello again. I did not resit and tried to install it according to the instruction above. Everything goes well untill 'poetry install', that returned the message 'Invalid version '0.1.43ubuntu1' on package python-debian'.
I'm on Mint 21.1 that is based on Ubuntu 21.04.1.
'

**Comment by stewartadam** [comment]
Hm, that appears to be a known issue and should only issue a deprecation warning, not an error - if you can paste the console output to a gist I can take a look and see what might be going on.

**Comment by didier33170** [comment]
Thank you for your help. Here is the screen-shot of the command in the terminal:
![poetry_install](https://user-images.githubusercontent.com/63016910/211671551-9df7400f-4440-4e1b-a563-070516f3562b.png)
I also sent the details of my configuration as a reply to the message I received on my email address, if it can help.

**Comment by stewartadam** [comment]
Hm, looks like this is known to both poetry and debian and neither has implemented a suitable fix, so I've disabled system site packages. It should work now after a `git pull`.

**Comment by didier33170** [comment]
Thanks for your effort. However, I must admit that I'm beyond the limit of my knowledge at this point...

**Comment by saiballo** [comment]
I tried to install but I had problems on poetry install. I'm on ubuntu 22.04 mint

`RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
`

**Comment by stewartadam** [comment]
I installed Fedora 37 and Ubuntu 22.04 to test and ran into that as well, Ubuntu and Fedora both carry the older 1.1 version of poetry that is not compatible with groups. I've reworked the poetry configuration to remain compatible with Poetry 1.1 to avoid the errors.

I just pushed out a final round of fixes and I'm at a point where I'm pretty comfortable with the Py3/GTK4 port, so I'm releasing it as 1.43.8-rc1! I've requested fwbackups be submitted to flathub (https://github.com/flathub/flathub/pull/3827), but in the interim I've also uploaded a flatpak image here: [com.diffingo.fwbackups-1.43.8-rc1.flatpak](https://downloads.diffingo.com/fwbackups/com.diffingo.fwbackups-1.43.8-rc1.flatpak).

**Comment by stewartadam** [comment]
Given 1.43.8-rc1 is fully Python 3/GTK 4 compatible, I'm going to mark the issue as closed and encourage submitting new issues for further enhancement or bug reports with the GTK4 port - but that doesn't mean the discussion has to stop. I'll continue to monitor here for installation help.

Thanks for continuing to use fwbackups! It means a lot to me.

**Comment by didier33170** [comment]
Sorry to contact you again with an issue. I did successfully a 'One-Time Backup'. Then I configured a backup set for my usual every day backup.
The Log Viewer report the following message:
"ERROR : Process exited with status 1. Errors: Can't find bus: Impossible de lancer automatiquement D-Bus sans $DISPLAY X11"

I case it can help, here is the result of $DISPLAY in the terminal:
   :0 : commande introuvable

Thank you any help!
